### ISSUE TITLE
Enable "proper" PR flow when there is a second contributor

### ISSUE THREAD

**Issue by AFulgens** [ShellMagick/commit-hooks#13]
### Context

PR flow with a pipeline after approval is not feasable with one contributor, because you cannot approve your own PRs [1].

### To do

When there is a second contributor to the project, consider the following:

* add trigger `workflow_call:` to `main.yml`
* add `pr-reviewed.yml`:
```yaml
name: PR approved
on:
  pull_request_review:
    types:
      - submitted

jobs:
  pr-approved:
    if: github.event.review.state == 'APPROVED'
    name: PR has been reviewed and approved, run main pipeline before merge
    uses: ./.github/workflows/main.yml
```
* enable mandatory review for PRs.

[1] https://github.com/orgs/community/discussions/6292
